version: "3.9"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ai-kb-backend
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - APP_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/aikb
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ai-kb-frontend
    ports:
      - "5000:5000"
    environment:
      # IMPORTANT: inside Docker, use the service name "backend" (not localhost)
      - API_SERVER_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: ai-kb-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aikb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
