version: "3.9"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ai-kb-backend
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - APP_ENV=development
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ai-kb-frontend
    ports:
      - "5000:5000"
    environment:
      # IMPORTANT: inside Docker, use the service name "backend" (not localhost)
      - API_SERVER_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
